name: Build Artifact

on:
  push:
    branches:
      - "main"

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Generate Version
        id: version
        run: |
          VERSION="2.0.${{ github.run_number }}-${{ github.run_attempt }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Register Build Artifacts in Cloudbees Platform
        uses: cloudbees-io-gha/register-build-artifact@v3.0.2
        id: go-action
        with:
          name: "App13-Backend-1"
          version: ${{ steps.version.outputs.version }}
          url: docker.io/App13/App13-Backend:${{ steps.version.outputs.version }}
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          label: "asjhgdxkuasahjbsdljAKsdbajkbiuawyedoucgqwyeugqwed"
          

          
